### ISSUE TITLE
I got a bug from your example

### ISSUE THREAD

**Issue by li195111** [virus-warnning/twnews#47] opened 2018-12-20 11:08 UTC
I use the example - News Search and Break down.
Totally copy the code and got a bug.
Maybe you should fix it:)
my environ :
python 3.6.6
Windows 10

InvalidURL
Failed to parse: m.ltn.com.twD:\news\society\breakingnews\2581807

**Comment by virus-warnning** [comment] 2018-12-21 07:15
Could you close this issue and create another issue with bug template?

**Comment by virus-warnning** [comment] 2019-02-15 06:46
Cannot reproduce the problem. Close Issue.

**Closed by virus-warnning** 2019-02-15 06:46 UTC
Labels: bug
